<a href="https://colab.research.google.com/github/mohammedabidali1956/Numpy/blob/main/AdvancedNumpyOp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Broadcasting In Numpy:*** Broadcasting in NumPy is
a mechanism that allows arithmetic operations between arrays of different shapes without needing to manually reshape them or create redundant copies of data.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr+10)

[11 12 13]


In [5]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([10,20,30])
print(matrix+vector)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


**Aggregation Functions:**

*   Aggregation functions computre summary statsistics for arrays
*   Common Functions



In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("Sum: ",np.sum(arr))
print("Max: ",np.max(arr))
print("Min: ",np.min(arr))
print("Standard Deviation: ",np.std(arr))
print("Mean: ",np.mean(arr))
print("Sum along rows: ",np.sum(arr,axis=1))
print("Sum along columns: ",np.sum(arr,axis=0))


[[1 2 3]
 [4 5 6]]
Sum:  21
Max:  6
Min:  1
Standard Deviation:  1.707825127659933
Mean:  3.5
Sum along rows:  [ 6 15]
Sum along columns:  [5 7 9]


**Boolean Indexing and Filtering :**


In [8]:
arr = np.array([1,2,3,4,5,6])

evens = arr[arr % 2 ==0]
print("Evens: ", evens)

arr[arr>3]=0
print("Modified Array ",arr)

Evens:  [2 4 6]
Modified Array  [1 2 3 0 0 0]


Random Numbers Genreation and Setting seeds

In [16]:
#random number genreation

#setting the seed
np.random.seed(42)

random_array = np.random.rand(3,3)
print("Random array :",random_array)

random_int = np.random.randint(0,15,size=(3,3))
print("Random Interger: ",random_int)

Random array : [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Random Interger:  [[ 7  2  5]
 [ 4  1  7]
 [11 13  5]]


HANDS ON EXERCISE

In [18]:
#EX: 1 broadcasting operations

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([1,0,-2])
print("Addition = \n",matrix + vector)
print("Multiplication =\n",matrix * vector)

Addition = 
 [[2 2 1]
 [5 5 4]
 [8 8 7]]
Multiplication =
 [[  1   0  -6]
 [  4   0 -12]
 [  7   0 -18]]


In [20]:
#EX 2 Generate and filter random dataset

#genrate random dataset
dataset = np.random.randint(1,52,size=(5,5))
print("Original Dataset\n:",dataset)

# filtering the dataset
dataset[dataset>25]=0
print("Modified dataset:\n",dataset)

#calculating summary statistics
print("Sum: \n",dataset.sum())
print("Mean: \n",dataset.mean())
print("Standard Devaition: \n",dataset.std())

Original Dataset
: [[25 14 50  9 26]
 [ 2 20 28 47  7]
 [44  8 47 35 14]
 [17 36 50 40  4]
 [ 2  6 42  4 29]]
Modified dataset:
 [[25 14  0  9  0]
 [ 2 20  0  0  7]
 [ 0  8  0  0 14]
 [17  0  0  0  4]
 [ 2  6  0  4  0]]
Sum: 
 132
Mean: 
 5.28
Standard Devaition: 
 7.152733743122275


Additional Practise

In [22]:
# Create a 3d random array and compute statistics along specific axes

# random array
matrix = np.random.randint(1,50,size=(3,3))
print(matrix)
print("add_axis=0: ",matrix.sum(axis=0))
print("add_axis=1: ",matrix.sum(axis=1))

[[15  8 14]
 [23 40 21]
 [16 45 18]]
add_axis=0:  [54 93 53]
add_axis=1:  [37 84 79]
