<a href="https://colab.research.google.com/github/mohammedabidali1956/Numpy/blob/main/Linear_Algebra_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vectors and Matrices
* Vector
  * Example:[2,3,4]
* Matrix
  * [1 2]

    [3 4]
* Properties

In [3]:
import numpy as np

matrix = np.array([[1,2],[3,4]])
vector = np.array([1,2,3])
print("Matrix:\n",matrix)
print("Vector:\n",vector)

Matrix:
 [[1 2]
 [3 4]]
Vector:
 [1 2 3]


Matrix Operations
* Addition and Subtraction
* Scalar Multiplication
* Matrix Multiplication

In [14]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[9,8],[7,6],[5,4]])

print("Matrix A:\n",A)
print("Matrix B:\n",B)

# Addition and Subtraction
print("Addition:\n",A+B)
print("Subtraction:\n",A-B)

#Scalar Multiplication
print("Scalar multiplication:\n",3*A)

# Martrix Multiplication
C = np.array([[1,2],[3,4],[5,6]])
D = np.array([[9,8,7],[7,6,5]])
result = np.dot(C,D)
print("Matrix Multiplication:\n",result)

Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Matrix B:
 [[9 8]
 [7 6]
 [5 4]]
Addition:
 [[10 10]
 [10 10]
 [10 10]]
Subtraction:
 [[-8 -6]
 [-4 -2]
 [ 0  2]]
Scalar multiplication:
 [[ 3  6]
 [ 9 12]
 [15 18]]
Matrix Multiplication:
 [[23 20 17]
 [55 48 41]
 [87 76 65]]


Special Matrices
* Identity Matrix (𝐼)
* 𝐼 ⋅ A = A
* Zero Matrix (0)
* Diagonal Matrix

In [23]:
# Identity Matrix
I = np.eye(3)
print("Identity Matrix:\n", I)

# Zero Matrix
Z = np.zeros((3,2))
print("Zero Matrix:\n",Z)

# Diagonal Matrix
D = np.diag([1,2,3])
print("Diagonal Matrix:\n",D)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


Hands-On Exercises

In [31]:
# Exercise 1: Create Vectors and Matrices Using NumPy

# Exercise 2: Implement Matrix-Vector Multiplication
import numpy as np

#creating a matrix and vector
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
vect = np.array([4,6,8])
res = np.dot(mat,vect)
# print(res)

# Exercise 3: Explore Special Matrices

# Identity Matrix X A
I = np.eye(3)
a = np.array([[1,2,3],
 [3,4,5],
  [5,6,7]])
result = np.dot(I,a)
print("I X A =\n",result)
# Diagonal and Zeros MAtrix


I X A =
 [[1. 2. 3.]
 [3. 4. 5.]
 [5. 6. 7.]]


Additional Practise

In [34]:
# Compute the determinant and inverse of a 2×2 matrix using NumPy

import numpy as np
A = np.array([[1,2],[3,4]])
det_a = np.linalg.slogdet(A)
print(det_a)

SlogdetResult(sign=np.float64(-1.0), logabsdet=np.float64(0.6931471805599455))
