<a href="https://colab.research.google.com/github/mohammedabidali1956/Numpy/blob/main/Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

This is how we import numpy and use arrays

In [ ]:
arr = np.array([1,2,3,4,5])
print(type(arr))


<class 'numpy.ndarray'>


Using built-in functions:
*   array of zeros
*   array of ones



In [ ]:
zeros = np.zeros([3,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


-> using arange  function for getting array with specific range and steps



In [ ]:
range_array = np.arange(1,50,4)
print(range_array)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49]


linspace: The numpy.linspace() function creates an array of evenly spaced numbers over a specified interval.

Example
Basic Usage: Create an array of 5 evenly spaced numbers between 0 and 10, inclusive

In [ ]:
lin_space = np.linspace(0,10,5)
print(lin_space)

[ 0.   2.5  5.   7.5 10. ]


Manipulation of Arrays:


*   Changing shape
*   add Dimensions



In [ ]:
# changing shape:
sam_array = np.array([1,2,3,4,5,6])
reshaped = sam_array.reshape(2,3)  #(row , column) --> (horizontal , vertical)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
# ading dimensions
arr = np.array([1,2,3])

expanded = arr[:,np.newaxis]

swap_expanded = arr[np.newaxis,:]

print(expanded)
print(swap_expanded)

[[1 2 3]]
[[1]
 [2]
 [3]]


Basic oerations on arrays

*   Element Wise Operations
*   Mathematical Operations



In [ ]:
# Element wise operations

#basic
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

arr = np.array([4,16,25])
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))


[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]
[0.2        0.33333333 0.42857143]
[2. 4. 5.]
45
15.0
25
4


Array indexing slicing and reshaping

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])
print(arr[1])
print(arr[:3])
print(arr[2:])
print(arr[2:4])

reshaped = arr.reshape(3,2)
print(reshaped)

6
2
[1 2 3]
[3 4 5 6]
[3 4]
[[1 2]
 [3 4]
 [5 6]]


Hands on Exercise

In [ ]:
# EX-1: Genreate array for basic mathematical operations

arr1 = np.arange(1,6)
arr2  =np.arange(6,11)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


In [ ]:
# EX:2 create a 3X3 matrix and peroform operations

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Matrix:\n",matrix)

transposed_matrix = matrix.T
print("Transposd Matrix:\n",transposed_matrix)

dusra_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Addition:\n",matrix + dusra_matrix)
print("Multiplication:\n",matrix * dusra_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposd Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Additional Practise

In [ ]:
# 1. create a 4X4 matrix and calculate the sum of its rows and columns

matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("Matrix:\n",matrix)
print("\nAdditiom: \n", matrix.sum())
print("\nAddition of Columns:\n",matrix.sum(axis=0))
print("\nAddition of Rows:\n",matrix.sum(axis=1))

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Additiom: 
 136

Addition of Columns:
 [28 32 36 40]

Addition of Rows:
 [10 26 42 58]


2. Write an program to normalize an array [scale value between 0 and 1]

$x_{normalized}=\frac{x-min}{max-min}$


In [ ]:
arr = np.array([10,20,30,40])
min_array = np.min(arr)
max_array = np.max(arr)
normalize = (arr-min_array)/(max_array-min_array)
print(normalize)

[0.         0.33333333 0.66666667 1.        ]


In [ ]:
# 3. Genrate a random array an dfind its max and min vales

arr = np.random.randint(1,100,size = 5)
print(arr)
print("Min of array:\t",np.max(arr))
print("Min of array:\t",np.min(arr))

[50 40 99 25 15]
Min of array:	 99
Min of array:	 15
